"""
Research note auto-writer — save each discovered idea to Obsidian/Research/.

Each note contains:
  - Source + URL
  - Extracted summary
  - Tags
  - Link to pair profile (if a pair is mentioned)
  - Placeholder sections: Hypothesis, Backtest Plan, Status
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from loguru import logger


def _vault_research_dir() -> Path | None:
    try:
        from config.settings import settings
        if settings.obsidian_vault_path and settings.obsidian_aria_folder:
            p = Path(settings.obsidian_vault_path) / settings.obsidian_aria_folder / "Research"
            p.mkdir(parents=True, exist_ok=True)
            return p
    except Exception:
        pass
    return None


def _detect_pair(text: str) -> str | None:
    """Detect a forex pair mention in the text."""
    import re
    PAIRS = ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "AUDUSD", "USDCAD",
             "NZDUSD", "USDCHF", "GBPJPY", "EURJPY"]
    txt_up = text.upper()
    for p in PAIRS:
        if p in txt_up:
            return p + "m"
    return None


def write_research_note(idea: dict[str, Any]) -> Path | None:
    """Write a single research idea to Obsidian/Research/. Returns the file path."""
    out_dir = _vault_research_dir()
    if not out_dir:
        return None

    title    = idea.get("title", "Untitled")[:80].replace("/", "-").replace("\\", "-").replace(":", "-")
    summary  = idea.get("summary", "")
    source   = idea.get("source", "Unknown")
    url      = idea.get("url", "")
    tags     = idea.get("tags", [])
    ts       = datetime.now().strftime("%Y-%m-%d %H:%M")
    pair     = _detect_pair(title + " " + summary)
    pair_link = f"\n\nRelated pair: [[Pair Profiles/{pair}]]" if pair else ""

    slug = datetime.now().strftime("%Y%m%d_%H%M%S_") + re.sub(r"[^a-z0-9_]", "_", title.lower())[:40]

    content = f"""# Research: {title}
*Extracted: {ts} | Source: {source}*

## Summary
{summary}

## Source
- URL: {url}
- Tags: {', '.join(tags)}
{pair_link}

## Hypothesis
> _To be filled after AI analysis_

- **Pair:** {pair or 'TBD'}
- **Timeframe:** M15
- **Signal logic:** TBD
- **Expected edge:** TBD
- **Risk notes:** TBD

## Backtest Plan
- [ ] Run basic backtest (90d)
- [ ] Walk-forward validation
- [ ] Monte Carlo gate

## Status
`pending` — added to hypothesis queue for evaluation

---
*Auto-generated by ARIA Research Engine*
"""

    import re
    fname = out_dir / f"{slug}.md"
    try:
        fname.write_text(content, encoding="utf-8")
        logger.info(f"[Research] Note written: {fname.name}")
        return fname
    except Exception as e:
        logger.warning(f"[Research] Note write failed: {e}")
        return None


def write_all_notes(ideas: list[dict[str, Any]]) -> list[Path]:
    """Write notes for a batch of ideas. Returns list of written paths."""
    import re
    paths = []
    for idea in ideas:
        p = write_research_note(idea)
        if p:
            paths.append(p)
    return paths
