"""
Risk Event Log — appends every halt/block/cooldown/emergency event to Obsidian.

File: <vault>/03 Projects/ARIA/Risk Log.md
Format: append-only Markdown, one H2 block per event.

Call append_event() from capital.py, emergency.py — never blocks the caller
(any vault write failure is silently swallowed via try/except).
"""

from __future__ import annotations

import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from loguru import logger

_lock = threading.Lock()

# Event type labels (kept short for the Markdown header)
HALT            = "HALT"
COOLDOWN        = "COOLDOWN"
LEVERAGE_BLOCK  = "LEVERAGE BLOCK"
EMERGENCY_CLOSE = "EMERGENCY CLOSE"
COOLDOWN_EXPIRED = "COOLDOWN EXPIRED"


def _log_path() -> Optional[Path]:
    try:
        from config.settings import settings
        return settings.obsidian_vault_path / settings.obsidian_aria_folder / "Risk Log.md"
    except Exception:
        return None


def _ensure_header(path: Path) -> None:
    """Create the file with a header if it doesn't exist."""
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# ARIA Risk Event Log\n"
            "*Append-only — auto-generated by ARIA risk engine*\n\n"
            "---\n\n",
            encoding="utf-8",
        )


def append_event(
    event_type: str,
    details:    str,
    balance:    Optional[float] = None,
    extra:      Optional[dict]  = None,
) -> None:
    """
    Append a risk event to the Obsidian Risk Log.
    Non-blocking: silently fails if vault is unavailable.
    """
    try:
        path = _log_path()
        if path is None:
            return

        now = datetime.now(timezone.utc)
        ts  = now.strftime("%Y-%m-%d %H:%M:%S UTC")

        lines = [f"## {ts} — {event_type}\n"]
        lines.append(f"**Details:** {details}\n")
        if balance is not None:
            lines.append(f"**Balance:** ${balance:,.2f}\n")
        if extra:
            for k, v in extra.items():
                lines.append(f"**{k}:** {v}\n")
        lines.append("\n---\n\n")

        block = "".join(lines)

        with _lock:
            _ensure_header(path)
            with path.open("a", encoding="utf-8") as f:
                f.write(block)

        logger.debug(f"[RiskLog] {event_type}: {details[:80]}")

    except Exception as e:
        logger.debug(f"[RiskLog] Write failed: {e}")
