"""
Multi-pair backtest — runs the same strategy across all configured pairs
and aggregates the results into a portfolio summary.

CLI:
  python -m backtest.multi_pair --days 90 --score 70

Output:
  - Per-pair table (trades, WR, PF, DD, P&L)
  - Portfolio aggregated stats
  - Saves to Obsidian: ARIA/Backtests/multi-YYYY-MM-DD.md
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from typing import Optional

from loguru import logger

from backtest.engine import BacktestEngine, BacktestResults
from config.settings import settings


def run_multi(
    pairs:   Optional[list[str]] = None,
    days:    int   = 90,
    score:   float = 70.0,
    risk:    float = 1.0,
) -> dict[str, BacktestResults]:
    """Run backtest for each pair. Returns {pair: BacktestResults}."""
    pairs = pairs or settings.pairs
    results: dict[str, BacktestResults] = {}

    for pair in pairs:
        logger.info(f"[MultiPair] Running {pair}...")
        try:
            engine = BacktestEngine(
                pair=pair,
                days=days,
                min_score=score,
                risk_pct=risk,
            )
            results[pair] = engine.run()
        except Exception as e:
            logger.error(f"[MultiPair] {pair} failed: {e}")

    return results


def _aggregate(results: dict[str, BacktestResults]) -> dict:
    """Compute portfolio-level stats from individual pair results."""
    all_trades  = [t for r in results.values() for t in r.trades]
    total_pnl   = sum(r.final_balance - r.initial_balance for r in results.values())
    total_wins  = sum(1 for t in all_trades if t.pnl > 0)
    total_trades = len(all_trades)
    win_rate     = total_wins / total_trades * 100 if total_trades else 0.0
    gross_profit = sum(t.pnl for t in all_trades if t.pnl > 0)
    gross_loss   = abs(sum(t.pnl for t in all_trades if t.pnl < 0))
    pf           = gross_profit / gross_loss if gross_loss > 0 else 0.0

    return {
        "total_trades":  total_trades,
        "total_wins":    total_wins,
        "win_rate":      round(win_rate, 1),
        "total_pnl":     round(total_pnl, 2),
        "profit_factor": round(pf, 2),
        "gross_profit":  round(gross_profit, 2),
        "gross_loss":    round(gross_loss, 2),
        "pairs_traded":  len([r for r in results.values() if r.trades]),
    }


def _build_report(results: dict[str, BacktestResults], days: int, score: float) -> str:
    agg = _aggregate(results)
    dt  = datetime.now(timezone.utc)
    date_str = dt.strftime("%Y-%m-%d")

    rows = ""
    for pair, r in sorted(results.items(), key=lambda x: x[1].total_pnl, reverse=True):
        from backtest.metrics import compute_metrics
        m = compute_metrics(r.trades, r.equity_curve, r.initial_balance, days)
        n = len(r.trades)
        wr = r.win_rate
        pf = m.get("profit_factor", 0.0)
        dd = m.get("max_drawdown_pct", 0.0)
        pnl = r.total_pnl
        rows += f"| {pair.rstrip('m')} | {n} | {wr:.0f}% | {pf:.2f} | {dd:.1f}% | ${pnl:+.2f} |\n"

    return f"""---
tags: [ARIA, backtest, multi-pair]
date: {date_str}
days: {days}
min_score: {score}
---

# ARIA Multi-Pair Backtest — {date_str}
*{days} days | Min score: {score} | {agg['pairs_traded']} pairs*

## Portfolio Summary

| Metric | Value |
|--------|-------|
| Total trades | `{agg['total_trades']}` |
| Win rate | `{agg['win_rate']:.1f}%` |
| Profit factor | `{agg['profit_factor']:.2f}` |
| Net P&L | `${agg['total_pnl']:+.2f}` |
| Gross profit | `${agg['gross_profit']:.2f}` |
| Gross loss | `${agg['gross_loss']:.2f}` |

## Per-Pair Results

| Pair | Trades | WR | PF | Max DD | P&L |
|------|--------|----|----|--------|-----|
{rows}
---
*[[ARIA Overview]] | Auto-generated by ARIA multi-pair backtest*
"""


def _save_to_obsidian(report: str) -> None:
    try:
        dt   = datetime.now(timezone.utc)
        path = (
            settings.obsidian_vault_path
            / settings.obsidian_aria_folder
            / "Backtests"
            / f"multi-{dt.strftime('%Y-%m-%d')}.md"
        )
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(report, encoding="utf-8")
        logger.info(f"Multi-pair report saved: {path.name}")
    except Exception as e:
        logger.warning(f"Obsidian save failed: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="ARIA Multi-Pair Backtest")
    parser.add_argument("--days",  type=int,   default=90)
    parser.add_argument("--score", type=float, default=70.0)
    parser.add_argument("--risk",  type=float, default=1.0)
    parser.add_argument("--pairs", nargs="+",  default=None,
                        help="Pairs to test (default: all configured pairs)")
    args = parser.parse_args()

    from data.mt5_feed import feed
    feed.connect()

    results = run_multi(pairs=args.pairs, days=args.days, score=args.score, risk=args.risk)
    agg     = _aggregate(results)

    print(f"\n=== MULTI-PAIR BACKTEST RESULTS ===")
    print(f"Pairs: {', '.join(results.keys())}")
    print(f"Trades: {agg['total_trades']} | WR: {agg['win_rate']:.1f}% | PF: {agg['profit_factor']:.2f}")
    print(f"Net P&L: ${agg['total_pnl']:+.2f}")

    report = _build_report(results, args.days, args.score)
    _save_to_obsidian(report)
    print("\nSaved to Obsidian.")
