"""
Monthly Learning Report — auto-generated on the 1st of each month at 00:05 UTC.

Rules-based, $0 AI cost. Pulls from pattern library, adaptive learning,
ML performance tracker, and trade history.

Writes to: Obsidian/03 Projects/ARIA/Lessons Learned/YYYY-MM.md
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

from loguru import logger


def build_monthly_report(year: int, month: int) -> str:
    from ml.performance import tracker as ml_perf
    from core.adaptive_learning import adaptive
    from core.pattern_library import get_patterns
    from core.mistake_detector import detect_mistakes
    from core.performance_attribution import attribution_summary

    dt_label  = f"{year}-{month:02d}"
    dt_start  = datetime(year, month, 1, tzinfo=timezone.utc)
    next_month = (dt_start.replace(day=28) + timedelta(days=4)).replace(day=1)
    dt_end    = next_month - timedelta(seconds=1)

    # Pull monthly trades from DB
    trades = _month_trades(dt_start, dt_end)
    total  = len(trades)
    wins   = sum(1 for t in trades if t["pnl"] > 0)
    wr     = wins / total * 100 if total else 0.0
    pnl    = sum(t["pnl"] for t in trades)
    gp     = sum(t["pnl"] for t in trades if t["pnl"] > 0)
    gl     = abs(sum(t["pnl"] for t in trades if t["pnl"] < 0))
    pf     = gp / gl if gl > 0 else 0.0

    ml_stats  = ml_perf.get_stats()
    patterns  = get_patterns()
    al_stats  = adaptive.all_stats()
    mistakes  = detect_mistakes()
    attr_text = attribution_summary()

    high_mistakes  = [m for m in mistakes if m["severity"] == "high"]
    med_mistakes   = [m for m in mistakes if m["severity"] == "medium"]

    mistake_section = ""
    for m in high_mistakes + med_mistakes:
        icon = "[HIGH]" if m["severity"] == "high" else "[MED]"
        mistake_section += f"- {icon} {m['message']} *(stat: {m['stat']})*\n"
    if not mistake_section:
        mistake_section = "*No systematic mistakes detected this month.*\n"

    al_rows = ""
    for pair, ps in sorted(al_stats.items(), key=lambda x: x[1].win_rate, reverse=True):
        al_rows += (f"| {pair} | {ps.wins}W/{ps.losses}L | {ps.win_rate:.0f}% | "
                    f"`{ps.min_score:.0f}` | `{ps.lot_multiplier:.2f}x` | `${ps.avg_pnl:+.2f}` |\n")

    drift = patterns.get("drift", {})

    return f"""---
tags: [ARIA, learning, monthly-review]
date: {dt_label}
trades: {total}
pnl: {pnl:.2f}
win_rate: {wr:.1f}
---

# ARIA Monthly Report — {dt_label}
*Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*

---

## 1. Month Summary

| Metric | Value |
|--------|-------|
| Total trades | `{total}` |
| Wins / Losses | `{wins}W / {total - wins}L` |
| Win rate | `{wr:.1f}%` |
| Net P&L | `${pnl:+.2f}` |
| Profit factor | `{pf:.2f}` |

## 2. ML Model Health

| Bucket | Trades | Win Rate |
|--------|--------|----------|
| Boosted | {ml_stats['boosted_trades']} | {ml_stats['boosted_wr']:.1f}% |
| Penalized | {ml_stats['penalized_trades']} | {ml_stats['penalized_wr']:.1f}% |
| Neutral | {ml_stats['neutral_trades']} | {ml_stats['neutral_wr']:.1f}% |

**Verdict:** {ml_stats['verdict']}

## 3. Pattern Library Drift

{patterns.get('total_trades', 0)} total trades | Drift: {drift.get('wr_delta', 0):+.1f}pp ({drift.get('label', '—')})

## 4. Adaptive Learning State

| Pair | W/L | WR | Min Score | Lot Mult | Avg P&L |
|------|-----|----|-----------|----------|---------|
{al_rows or '*No data.*'}

## 5. Systematic Mistakes

{mistake_section}

## 6. Performance Attribution

```
{attr_text}
```

## 7. Action Items for Next Month

- [ ] Address any HIGH severity mistakes above
- [ ] Review pairs with WR < 40% — consider removing from watchlist
- [ ] Validate ML model if verdict is negative — consider retraining
- [ ] Review adaptive learning thresholds — are they converging?

---
*[[ARIA Overview]] | Auto-generated by ARIA monthly report engine*
"""


def _month_trades(start: datetime, end: datetime) -> list[dict]:
    try:
        from db.session import get_session
        from db.models import Trade
        with get_session() as db:
            trades = (db.query(Trade)
                      .filter(Trade.status == "closed",
                              Trade.opened_at >= start,
                              Trade.opened_at <= end)
                      .all())
            return [{"pair": t.pair, "pnl": t.pnl or 0.0, "direction": t.direction}
                    for t in trades]
    except Exception:
        return []


def write_monthly_report(year: int, month: int) -> None:
    try:
        from config.settings import settings
        content    = build_monthly_report(year, month)
        label      = f"{year}-{month:02d}"
        folder     = settings.obsidian_vault_path / settings.obsidian_aria_folder / "Lessons Learned"
        path       = folder / f"{label}.md"
        folder.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        logger.info(f"Monthly report written: {path.name}")
    except Exception as e:
        logger.error(f"Monthly report failed: {e}")
