"""
Obsidian vault writer — writes ARIA outputs to the shared AyoubOS vault.

Vault path: D:/A office/AyoubOS/02-Obsidian-Vault
ARIA folder: 03 Projects/ARIA/

Creates:
  03 Projects/ARIA/Trades/YYYY-MM-DD-PAIR.md   — per-trade notes
  03 Projects/ARIA/Analysis/YYYY-MM-DD.md       — pre-session analysis
  01 Daily Notes/Trading/YYYY-MM-DD.md          — daily trading log
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from loguru import logger

from config.settings import settings
from core.capital import DayStats


class ObsidianWriter:
    """Writes ARIA outputs as Markdown notes to the shared Obsidian vault."""

    def __init__(self) -> None:
        self.vault   = settings.obsidian_vault_path
        self.trades  = settings.obsidian_trades_path
        self.daily   = settings.obsidian_daily_path
        self.analysis = settings.obsidian_analysis_path

    def _write(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        logger.debug(f"Vault write: {path.relative_to(self.vault)}")

    # ── Trade Notes ───────────────────────────────────────────────────────────

    def write_trade(
        self,
        pair: str,
        direction: str,
        entry: float,
        sl: float,
        tp1: float,
        tp2: float,
        tp3: float,
        lots: float,
        score: float,
        reason: str,
        ticket: int,
        dt: Optional[datetime] = None,
    ) -> None:
        """Write a trade note to the vault."""
        dt = dt or datetime.now(timezone.utc)
        date_str = dt.strftime("%Y-%m-%d")
        time_str = dt.strftime("%H:%M UTC")
        filename  = f"{date_str}-{pair}-{direction.upper()}.md"
        path = self.trades / filename

        arrow = "↑ LONG" if direction == "long" else "↓ SHORT"
        content = f"""---
tags: [ARIA, trade, {pair}]
date: {date_str}
pair: {pair}
direction: {direction}
ticket: {ticket}
score: {score}
status: open
---

# {arrow} {pair} — {date_str}

| Field | Value |
|-------|-------|
| Entry | `{entry}` |
| Stop Loss | `{sl}` |
| TP1 (2R) | `{tp1}` |
| TP2 (4R) | `{tp2}` |
| TP3 (6R) | `{tp3}` |
| Lots | `{lots}` |
| Confluence | `{score:.0f}/100` |
| Ticket | `{ticket}` |
| Time | {time_str} |

## Reason
{reason}

## Outcome
*(update after close)*

| Field | Value |
|-------|-------|
| Exit price | — |
| P&L | — |
| Result | — |

## Notes

## Links
- [[Pair Profiles/{pair}]] — pair profile
- [[ARIA Overview]] — system overview

"""
        self._write(path, content)
        # Bi-directional: append backlink to pair profile
        self._add_trade_backlink_to_pair_profile(pair, filename, date_str)

    def update_trade_outcome(
        self,
        pair: str,
        direction: str,
        date_str: str,
        exit_price: float,
        pnl: float,
    ) -> None:
        """Update a trade note with the outcome after close."""
        filename = f"{date_str}-{pair}-{direction.upper()}.md"
        path = self.trades / filename
        if not path.exists():
            return

        content = path.read_text(encoding="utf-8")
        result = "WIN" if pnl > 0 else "LOSS" if pnl < 0 else "BREAK EVEN"
        status = "closed"

        content = content.replace("status: open", f"status: {status}")
        content = content.replace("| Exit price | — |", f"| Exit price | `{exit_price}` |")
        content = content.replace("| P&L | — |", f"| P&L | `${pnl:+.2f}` |")
        content = content.replace("| Result | — |", f"| Result | **{result}** |")
        path.write_text(content, encoding="utf-8")

    # ── Session Analysis ──────────────────────────────────────────────────────

    def write_session_analysis(self, analysis: str, dt: Optional[datetime] = None) -> None:
        """Write pre-session analysis to vault."""
        dt = dt or datetime.now(timezone.utc)
        date_str  = dt.strftime("%Y-%m-%d")
        path = self.analysis / f"{date_str}-pre-session.md"

        content = f"""---
tags: [ARIA, analysis, pre-session]
date: {date_str}
---

# Pre-Session Analysis — {date_str}
*Generated by ARIA at {dt.strftime("%H:%M UTC")}*

{analysis}
"""
        self._write(path, content)

    # ── Daily Report ──────────────────────────────────────────────────────────

    def write_daily_report(
        self,
        report: str,
        day_stats: DayStats,
        dt: Optional[datetime] = None,
    ) -> None:
        """Write end-of-day report to daily notes."""
        dt = dt or datetime.now(timezone.utc)
        date_str = dt.strftime("%Y-%m-%d")
        path = self.daily / f"{date_str}.md"

        pnl_emoji = "📈" if day_stats.realized_pnl >= 0 else "📉"
        content = f"""---
tags: [ARIA, daily-log, trading]
date: {date_str}
pnl: {day_stats.realized_pnl:.2f}
trades: {day_stats.trades_taken}
win_rate: {day_stats.win_rate:.0f}
---

# ARIA Daily Log — {date_str}

## Stats {pnl_emoji}

| Metric | Value |
|--------|-------|
| P&L | `${day_stats.realized_pnl:+.2f}` |
| Trades | `{day_stats.trades_taken}` |
| Win Rate | `{day_stats.win_rate:.0f}%` |
| Profit Factor | `{day_stats.profit_factor:.2f}` |

## Report

{report}

---
*ARIA — Autonomous Research & Intelligent Allocation*
*[[ARIA Overview]]*
"""
        self._write(path, content)

    # ── Weekly Learning Report ────────────────────────────────────────────────

    def write_weekly_report(self, content: str, dt: datetime) -> None:
        """Write weekly learning report to Lessons Learned/ folder."""
        iso = dt.isocalendar()
        week_label = f"{iso[0]}-W{iso[1]:02d}"
        folder = self.vault / settings.obsidian_aria_folder / "Lessons Learned"
        path   = folder / f"{week_label}.md"
        self._write(path, content)
        logger.info(f"Weekly report written: {path.relative_to(self.vault)}")

    # ── Pair Profile ─────────────────────────────────────────────────────────

    def update_pair_profile(self, pair: str) -> None:
        """
        Auto-update per-pair profile note after every backtest.
        Writes to: ARIA/Pair Profiles/<PAIR>.md
        Pulls best session, score range, avg win from pattern library.
        """
        try:
            from core.pattern_library import get_patterns
            from core.adaptive_learning import adaptive
            from datetime import datetime, timezone

            patterns = get_patterns()
            by_pair  = patterns.get("by_pair", {})
            pair_stats = by_pair.get(pair, by_pair.get(pair.rstrip("m"), {}))

            al      = adaptive.all_stats().get(pair, None)
            by_sess = patterns.get("by_session", {})
            by_rg   = patterns.get("by_regime",  {})

            best_sess  = max(by_sess.items(), key=lambda x: x[1]["wr"], default=("—", {}))
            best_rg    = max(by_rg.items(),   key=lambda x: x[1]["wr"], default=("—", {}))

            n        = pair_stats.get("trades", 0)
            wr       = pair_stats.get("wr",     0.0)
            avg_pnl  = pair_stats.get("avg_pnl", 0.0)
            total_pnl = pair_stats.get("total_pnl", 0.0)
            al_score = f"`{al.min_score:.0f}`" if al else "—"
            al_mult  = f"`{al.lot_multiplier:.2f}×`" if al else "—"

            dt = datetime.now(timezone.utc)
            content = f"""---
tags: [ARIA, pair-profile, {pair}]
updated: {dt.strftime("%Y-%m-%d")}
pair: {pair}
---

# {pair.rstrip('m')} — Pair Profile
*Last updated: {dt.strftime("%Y-%m-%d %H:%M UTC")}*

## Live Statistics (All-Time)

| Metric | Value |
|--------|-------|
| Total trades | `{n}` |
| Win rate | `{wr:.1f}%` |
| Avg P&L / trade | `${avg_pnl:+.4f}` |
| Total P&L | `${total_pnl:+.2f}` |

## Adaptive Learning State

| Setting | Value |
|---------|-------|
| Min score threshold | {al_score} |
| Lot multiplier | {al_mult} |

## Best Conditions

| Dimension | Best |
|-----------|------|
| Session | {best_sess[0].capitalize()} ({best_sess[1].get('wr', 0):.0f}% WR) |
| Regime | {best_rg[0].upper()} ({best_rg[1].get('wr', 0):.0f}% WR) |

---
*[[ARIA Overview]] | Auto-updated by ARIA after each backtest*
"""
            folder = self.vault / settings.obsidian_aria_folder / "Pair Profiles"
            path   = folder / f"{pair.rstrip('m')}.md"
            self._write(path, content)
            logger.debug(f"Pair profile updated: {pair}")
        except Exception as e:
            logger.debug(f"Pair profile update failed for {pair}: {e}")

    # ── Bi-directional linking ────────────────────────────────────────────────

    def _add_trade_backlink_to_pair_profile(self, pair: str, trade_file: str, date_str: str) -> None:
        """Append a backlink to the pair profile whenever a new trade note is created."""
        try:
            folder = self.vault / settings.obsidian_aria_folder / "Pair Profiles"
            path   = folder / f"{pair.rstrip('m')}.md"
            if not path.exists():
                return
            content  = path.read_text(encoding="utf-8")
            link_line = f"- [[Trades/{trade_file.replace('.md','')}]] — {date_str}"
            if "## Recent Trades" in content:
                content = content.replace(
                    "## Recent Trades",
                    f"## Recent Trades\n{link_line}",
                )
            else:
                content += f"\n\n## Recent Trades\n{link_line}\n"
            path.write_text(content, encoding="utf-8")
        except Exception:
            pass

    # ── Vault Overview Note ───────────────────────────────────────────────────

    def ensure_overview(self) -> None:
        """Create/update the ARIA overview note in the vault if it doesn't exist."""
        path = self.vault / settings.obsidian_aria_folder / "ARIA Overview.md"
        if path.exists():
            return

        content = f"""---
tags: [ARIA, project, trading]
created: {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
---

# ARIA — Autonomous Research & Intelligent Allocation

ARIA is an autonomous FX & multi-asset trading system that:
- Analyses markets every 5 minutes using Smart Money Concepts + multi-timeframe bias
- Executes trades on MT5 demo accounts with 1% risk per trade
- Writes daily trading logs and analysis to this vault

## Folder Structure

- [[Trades/]] — per-trade notes (entry, SL, TP, outcome)
- [[Analysis/]] — pre-session and session analysis
- [[../Daily Notes/Trading/]] — daily P&L logs

## Key Config

| Setting | Value |
|---------|-------|
| Account | MT5 Demo |
| Risk/trade | 1% |
| Daily target | 5% |
| Max loss | 3% |
| Pairs | {', '.join(settings.pairs)} |

## Links
- [[Content Factory]] — other AyoubOS project
- [[CareerPilot]] — other AyoubOS project

---
*Managed by ARIA system — do not edit trade entries manually*
"""
        self._write(path, content)
